### ISSUE TITLE
jsConnect uses an http image, causing browser warnings on https forums

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#109]
jsConnect makes forums load http://cdn.vanillaforums.com/images/usericon_50.png. If the forum loads under HTTPS, this results in a mixed content warning in the browser. Unfortunately, https://cdn.vanillaforums.com/images/usericon_50.png doesn't appear properly set certificate-wise.

**Comment by linc** [comment]
Fixed
