### ISSUE TITLE
FileUpload: upload on edit

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#110]
Should be able to upload a file when editing a comment.

**Comment by hideheader** [comment]
No, it's a bug, not an enhancement. This did work once, now it doesn't.

**Comment by decembre** [comment]
Yes, can you do something about this "little" problem ?

**Comment by hideheader** [comment]
You can add an upload in the original post, but not in a comment. Please, afterthoughts are the best thoughts I have now.

**Comment by linc** [comment]
Waiting on #367

**Comment by hideheader** [comment]
Thank you. I've really missed having this.
