### ISSUE TITLE
Quotes does not escape user name

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#136]
Vanilla master branch, Quotes 1.6.1.

User names that contain HTML[1] are not escaped, so when someone quotes that user, the HTML takes effect in the post. XSS doesn't seem possible, because the post is limited to what users can post anyway. For example, quoting a user with the name `<b>yo</b>` will result in 

> **yo** said:

1: With normal user registration, user names are limited to "letters, numbers, underscores". With jsConnect, it can actually be anything.

**Comment by linc** [comment]
This was fixed.
