### ISSUE TITLE
Quotes 1.6.8 (from master) doesn't correctly display quotes made with 1.6.1 (latest release)

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#152]
1.6.1 uses the format:
```html
<blockquote rel="A person">Content</blockquote>
```

1.6.8 uses:
```html
<blockquote class="Quote" rel="A person">Content</blockquote>
```

When 1.6.8 sees the 1.6.1 format, it doesn't do it's thing - the content is styled as a plain `<blockquote>` without any change in background or indication of who is being quoted. This makes it suck to upgrade, as you lose the formatting on any previous content.

**Comment by linc** [comment]
Pretty certain we fixed this transition problem.
