### ISSUE TITLE
[G+ plugin] Fatal error on render

### ISSUE THREAD

**Issue by franga2000** [vanilla/addons#160]
Hi, I'm trying to get Google Plus auth working on my forum but I keep getting this PHP error:

```
PHP Fatal error:  Call to undefined function SocialSignInButton() in <forum-path>/plugins/GooglePlus/class.googleplus.plugin.php on line 150, referer: <forum-url>
```

The problem is in this function: [`class.googleplus.plugin.php` on line 150](https://github.com/vanilla/addons/blob/master/plugins/GooglePlus/class.googleplus.plugin.php#L150)

``` PHP
   public function SignInButton($type = 'button') {
      $Target = Gdn::Request()->Post('Target', Gdn::Request()->Get('Target', Url('', '/')));
      $Url = $this->AuthorizeUri(array('target' => $Target));

      $Result = SocialSignInButton('Google', $Url, $type); // <--- HERE
      return $Result;
   }
```

It seems to reference a function that doesn't exist and I don't think it's a typo since there aren't any functions that accept these parameters in the code.

Is this a W.I.P. feature or is there something I missed?
Also, when can we expect the plugin to be fixed?

**Comment by joeczucha** [comment]
Thank you for posting this, franga2000, as I've been pulling my hair out for the last few hours trying to solve this :( (2.1.8, downloaded earlier today from the website)
