### ISSUE TITLE
FileUpload Compatible with Version 2.1.7?

### ISSUE THREAD

**Issue by intrinsicforce** [vanilla/addons#176]
Hello! 
I just tried to install FileUpload, but i got this:
"The addon could not be enabled because it generated a fatal error: "
Is it compatible with V2.1.7?

Best regards!

**Comment by alexcroox** [comment]
It errors after a file upload for me, it doesn't like the base64 decoding part

 `var thumbnailHtml = jQuery.base64Decode(JResponse.MediaResponse.Thumbnail);`
` Uncaught TypeError: undefined is not a function`
