### ISSUE TITLE
Quotes & Markdown: post with a quote gives blank quote

### ISSUE THREAD

**Issue by linc** [vanilla/addons#179]
Say your post starts with a quote, followed by your reply. If someone then clicks Quote on YOUR post, they will get:

```
> You said:
>
```

and nothing more in the comment box.

**Comment by x00** [comment]
`_StripMarkdownQuotes` looks to the likely culprit.

**Comment by x00** [comment]
This is in the quotes plugin

**Comment by x00** [comment]
I'm actaully getting other error related to fetching the quote, that others have got.

`{"Code":400,"Exception":"DiscussionController->Discussion not found.","Class":"Exception"}`

I will need to test this pluign agaist 2.2 to see if that issue still exists.

**Comment by RodSloan** [comment]
I'm getting the same error on my implementation of 2.2. 
I managed to fix it by commenting out the line:
```
$QuoteBody = self::_stripMarkdownQuotes($QuoteBody);
```

**Comment by linc** [comment]
This is not an issue in 2.5.
