### ISSUE TITLE
Q&A: "Ask a Question" is not accessible

### ISSUE THREAD

**Issue by R-J** [vanilla/addons#197]
Those lines are commented out: https://github.com/vanilla/addons/blob/master/plugins/QnA/class.qna.plugin.php#L990-L1000 and that's why there is no dropdown possibility for "Ask a Question".

But there are no other options to start a question. Even when UseBigButtons is set to true, the Button is not rendered for DiscussionsController (but at least it is for CategoriesController and DiscussionController)

**Comment by linc** [comment]
I'm not following your bug report. The Base_DiscussionTypes_Handler event is what's adding "Ask a Question" as an option in the NewDiscussionModule.

**Comment by R-J** [comment]
When doing a full text search in Vanilla 2.1, I do not get a result for "DiscussionTypes", so I guess it is a new thing in Vanilla 2.2

**Comment by linc** [comment]
Oh, barf. Yeah, must be. Man things like this make me shake my head at how behind we are on getting open source caught up. :(

**Comment by R-J** [comment]
We **all** are yearning for the new version to come ;)

**Comment by linc** [comment]
Gonna close this since it'll be fixed by the 2.2 release.
