### ISSUE TITLE
Q&A: Changing a discussion to question after posting doesn't set QnA field

### ISSUE THREAD

**Issue by pavsid** [vanilla/addons#205]
Hi, I encountered this bug, where changing a discussion to a question after posting, doesn't display that question in the "unanswered" list. This is because the `QnA` field isn't updated when a discussion `Type` is changed.

My fix - update the `QnA` field along with the `Type` by adding..

```
'QnA' => ($Sender->Form->GetFormValue('Type') == 'Question' ? ($Discussion->CountComments > 0 ? 'Answered' : 'Unanswered') : NULL)
```

**Comment by DaazKu** [comment]
Fixed by https://github.com/vanilla/addons/commit/c349ef23762bdb2f2daad59733161a26dc07a107
