### ISSUE TITLE
Quotes should provide an area outside of the blockquote that a user can click into

### ISSUE THREAD

**Issue by emilynewsom** [vanilla/addons#223]
I am using Quotes 1.6.9. My Garden.InputFormatter is Wysiwyg. My custom theme injects tinymce 4 rather than relying on a wysiwyg module, but the results should be the same. When a user clicks the quote button a blockquote is inserted into the editor. If the user clicks into the editor, their cursor is now within the blockquote. They have to physically move down a few lines and remove the blockquote styling in order to start typing outside of the quote. What I am suggesting is a simple extra `<p></p>` inserted into the textarea after the blockquote. This allows the user to click outside of the quote and the problem is solved.

```
--- class.quotes.plugin.php
+++ class.quotes.plugin.php
@@ -370,7 +370,7 @@
   <div class="QuoteAuthor">$Attribution</div>
   <div class="QuoteText">$QuoteBody</div>
 </blockquote>
-
+<p></p>
 BLOCKQUOTE;

                break;
```

**Comment by linc** [comment]
This is fixed in 2.5.
