### ISSUE TITLE
Quotes scroll offset should be configurable

### ISSUE THREAD

**Issue by emilyanew** [vanilla/addons#224]
Within quotes.js, currently the scroll offset  of -100 is not configurable. Would be nice if this was adjustable somehow in order to allow for themes with larger fixed headers.

**Comment by charrondev** [comment]
This is a valid user story and is already handled with the strategy in our new theming system. `<ScrollOffsetProvider />` calculated the document offset of the `<TitleBar />` component which is sticky and always ensure scroll offsets are down below it.

This won't have any affect on the forum until we do a new theme using this component though (slated for beginning of 2020 currently) .
