### ISSUE TITLE
TrollManagement: Troll post causes a unknown user post to show up at the end of the thread for normal users

### ISSUE THREAD

**Issue by GhoulofGSG9** [vanilla/addons#230]
Whenever a troll posts in a tread a post of the user Unknown appears at the end of the given thread.

This is obviously some kind of bug and should be fixed if possible.

**Comment by linc** [comment]
Troll Management does not hide the "Latest Post" area from updating. I'm not sure what the "Unknown" part is, but you might want to ask for assistance on vanillaforums.org/discussions
