### ISSUE TITLE
Enhancement: Answer Own Question

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/addons#233]
It would make sense for a way to allow members (without being a moderator) to accept their own answer, but without gaining a point.

http://vanillaforums.org/discussion/30351/answer-own-question

**Comment by linc** [comment]
Duplicate of #67

**Comment by exitgames** [comment]
Closing this means you will not add this?

**Comment by adrianspeyer** [comment]
No. It was my fault for not finding that this had been requested earlier. As noted, it is under issue 67.
