### ISSUE TITLE
Q&A: Discussion presence in "Unanswered" view can be confusing.

### ISSUE THREAD

**Issue by initvector** [vanilla/addons#265]
### Seeking feedback!

If a Q&A discussion is added, it's initially flagged as "Unanswered" and shows up in the "Unanswered" discussion view.  Every time someone aside from the author posts to that discussion, the status is flipped to "Answered" and the message drops from the "Unanswered" list.  If the author comes in and rejects the post, the discussion status is flipped to "Rejected" and reappears in the "Unanswered" list.  If a post is ultimately chosen as an answer, the status is flipped to "Accepted".

This workflow can be confusing for some users who expect a Q&A discussion to remain in "Unanswered" until it has an accepted answer.  Users posting non-answer responses to the discussion can lower the visibility of the question.

The labeling can also be confusing.  While the internals of the plug-in know the difference between the unanswered, answered, accepted and rejected statuses, those aren't shown to users.  What a user sees when they accept an answer is their Q&A discussion being flagged as "Answered" (which is actually "Accepted" in the backend).  It doesn't seem unreasonable for them to expect to see their question in "Unanswered", until it's tagged as "Answered".

All that said, it may be a potential issue for larger forums to change the way things work now.  If a user never takes the time to flag their question as answered, it would indefinitely linger in the "Unanswered" list, despite having valid answers.

**Comment by R-J** [comment]
I wanted to post this as an issue right now. Not every comment is an answer. 

I posted a question and was very surprised to see that it is already marked as answered although I haven't even read the first comment to my question. 
I rejected it and was satisfied to see that it is unanswerd again. 
Afterwards I've posted an explanation to that discussion and now it is marked as answered. This is absurd. 

There is no automatism which is able to detect if a comment an answer or not. While not doing anything isn't always correct, at least it doesn't show absurd results...

**Comment by R-J** [comment]
I was thinking about that recently. It still feels unsatisfying to see a question is marked as Answered if there is no answer to the question, merely some guy saying "*I have the same question!*"

And I was just about to talk about two possible workarounds I could think of, when I found that one of them is already in place!

~~~
...
      $QnA = GetValue('QnA', $Discussion);
...
      switch ($QnA) {
...
         case 'Answered':
            $Text = 'Answered';
...
         case 'Accepted':
            $Text = 'Answered';
...
      }
      if ($QnA) {
         echo ' <span class="Tag QnA-Tag-'.$QnA.'"'.$Title.'>'.T("Q&A $QnA", $Text).'</span> ';
      }
~~~

That allows customizing to ones own wishes by translations:

~~~
$Definition['Q&A Answered'] = 'Question';
// $Definition['Q&A Accepted'] = 'Answered'; // no need for that since that is already default
~~~

or 

~~~
// $Definition['Q&A Answered'] = 'Answered';  // no need for that since that is already default
$Definition['Q&A Accepted'] = 'Solved';
~~~

The other possibility I was thinking of was using a config setting, but using translations is much more flexible

**Comment by chrisvanpatten** [comment]
If changing the default is under consideration, Answered/Solved seems like a far better default than what's currently there.

**Comment by R-J** [comment]
@chrisvanpatten: the good news is, that you can already use it like that. Just add `$Definition['Q&A Accepted'] = 'Solved';` to your `/conf/locale.php` file (and maybe you have to delete *.ini files in the `/cache` folder)

**Comment by chrisvanpatten** [comment]
@R-J Not on the hosted platform though :(

**Comment by chrisvanpatten** [comment]
(That sort of reminds me… why did the forum text changing plugin get effectively deprecated? This would be a perfect candidate for that. I saw in another GH issue that there were some problems, but I'm relatively new to the platform and not sure what the problems were. Performance issues?)
