### ISSUE TITLE
Remove NBBC's dependence on FileUpload

### ISSUE THREAD

**Issue by initvector** [vanilla/addons#277]
NBBC currently relies on [FileUpload to pull media/attachment information](https://github.com/vanilla/addons/blob/eacbaf07bed226b882c48847477c9f412fce2f73/plugins/NBBC/class.nbbc.plugin.php#L229).  This dependence isn't ideal and should be removed in favor of alternatives available in core.

**Comment by linc** [comment]
Addon is gone.
