### ISSUE TITLE
Multilingual: EN locale cannot be activated unless it's the default language

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/addons#359]
When activating multilingual the EN local does not have a toggle, so it can only be the default language. If you want to have English as a secondary language, the only option is the UK version (en_GB).

It can be fixed in the config by adding it to the enabled locales, such as:
    "EnabledLocales": {
        "vf_vi": "vi",
        **"vf_en": "en"**
    }

**Comment by vredeling** [comment]
The workaround in OP works but I think the multilingual module should have a setting: "keep EN locale enabled".

**Comment by vredeling** [comment]
@tburry @linc these stale issues are closed automatically and I reckon they're off the radar from that point onwards. Which is understandable but unfortunate given the small size of this community.
Is there a way for us to reopen existing issues instead of opening new ones?
