### ISSUE TITLE
Whispers: autosave causes whisper to be posted

### ISSUE THREAD

**Issue by phred** [vanilla/addons#36]
* Start writing a whisper on a discussion.
 * Let the autosave run.

Two things happen:

 * The whisper gets posted to the discussion
 * The browser gets redirected to a non-existent page.  For the discussion on our board I was redirected from:

http://forum.foxycart.com/discussion/2838/helpful-hints-for-your-first-post-read-this-first#Item_1
to: 
http://forum.foxycart.com/discussion/comment/37152?rand=93538#Comment_w38445

The latter 404's.  When I return to the discussion thread I do see that my whisper has been posted.

**Comment by linc** [comment]
Whispers is no longer in development.
