### ISSUE TITLE
Advanced Editor & Markdown format

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/addons#412]
When using Markdown in a post with an unordered list, paragraph tags are inserted for the first two list items. The same does not happen when using an ordered list.

Input Markdown:

```
Here's some text.

* list item 1
* list item 2
* list item 3
* list item 4
```

Once submitted, the above results in the following actual HTML when rendered:

```
<p>Here's some text.</p>

<ul>
<li><p>list item 1</p></li>
<li><p>list item 2</p></li>
<li>list item 3</li>
<li>list item 4</li>
</ul>
```

Notice how paragraph tags are added to the first two (and only the first two) list items for some reason. Lists should be consistent: if paragraph tags are going to be added, they should be added to all. However, it would be far more standard (and would actually follow the Markdown spec) to not insert paragraph tags at all.

**Comment by linc** [comment]
This was fixed in 2.5. Also, wrong repo.
