### ISSUE TITLE
jsConnect: Can't use '?' in authentication url

### ISSUE THREAD

**Issue by tfotis** [vanilla/addons#42]
if my authentication url includes an '?', the url built to handle the authentication is invalid.

for example let's say that the authentication url is http://www.example.com/index.php?module=Vanilla&func=authenticate. Then, jsConnect will append it's parameters without checking if the authentication url already has a '?'. The resulting url will be something like http://www.example.com/index.php?module=Vanilla&amp;func=authenticate?client_id=XXX&amp;timestamp=XXX&amp;signature=XXX&amp;Target=/settings/jsconnect (notice the 2 question marks?)

**Comment by linc** [comment]
@tburry This was resolved?
