### ISSUE TITLE
Answers authors points not recalculated properly when the answer is edited by an admin

### ISSUE THREAD

**Issue by beckyvb** [vanilla/addons#428]
EDIT
---
The Q&A menu options did not recalculate points properly when the status was changed.

-----

QnA's handling of reactions assumes that only one user will be managing the QnA status. It relies on the toggling nature of Reactions. (i.e., reacting once enables, reacting twice disables). This goes through the roof when another user comes in and changes the status of a question. When two users edit the status of an answer, it results in the comment author getting double the points.

Steps to reproduce:
1. Ensure Reactions is enabled and QnA points are enabled.
2. Accept a comment as an answer.
3. With another (admin) user, edit the QnA status to 'Rejected' or 'Don't Know'

Result:
There are two Accepted Answer reactions on the comment, resulting in the author being awarded double the points.

Expected result:
The comment author loses their points for the Accepted Answer.

**Comment by DaazKu** [comment]
The feature is utterly broken.

Points are not given on first answer.
Reactions point are not set properly when enabled/disabling the plugin.
Points are not given/removed properly when using the QnAOptions (admin tool)
Points are not given/removed properly when not using reactions.
