### ISSUE TITLE
Troll Management Enabled Causes Fatal Errror

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/addons#429]
When enabled plugin on latest master (Version 2.3.100), getting following in server error log:

`PHP Fatal error:  Only variables can be passed by reference in /home/xxxxx/public_html/plugins/TrollManagement/class.trollmanagement.plugin.php on line 246`

**Comment by linc** [comment]
Wish you'd flagged this to me. Didn't see it.

**Comment by adrianspeyer** [comment]
Sorry @linc didn't see it impacting the hosted stuff so I wasn't sure. Next time I'll flag on fatal error stuff.
