### ISSUE TITLE
TrollManagement not working ?

### ISSUE THREAD

**Issue by enjoyaol** [vanilla/addons#436]
Using Vanilla 2.2.1
I put the folder TrollManagement in my plugins folder.
I activated it on the dashboard.
I unlogged from the website, reopened it, and I see no option to mark users as 'Trolls' anywhere.

**Comment by DaazKu** [comment]
You have to remove addons.php from the cache folder.

**Comment by DaazKu** [comment]
Help request should be directed to [ Vanilla's community forum](https://vanillaforums.org/categories/vanilla-2-2).
