### ISSUE TITLE
ValidateWebAddress not validating http://web-site.com

### ISSUE THREAD

**Issue by x00** [vanilla/addons#45]
Dashes don't validate even though they are valid. Underscore could also be a problem. 

Please look at the URL spec

http://www.ietf.org/rfc/rfc1738.txt

it is becuase of this bug
https://bugs.php.net/bug.php?id=51192
https://bugs.php.net/bug.php?id=51258

I suggest that the versions of php with this bug are common enough to warrant replacing the characters before validating.

**Comment by linc** [comment]
This is fixed in PHP 5.3.3 and we are moving our requirements to 5.4.
