### ISSUE TITLE
Vanilla Analytics not loading remote.js

### ISSUE THREAD

**Issue by VrijVlinder** [vanilla/addons#455]
Vanilla Analytics is not finding the file :
`http://analytics.vanillaforums.com/applications/vanillastats/js/remote.js `

Results in 404

Problem with jQuery  Uncaught TypeError: Cannot set property 'src' of null  in vanillastats.js  

 ```
// Load the graph data
        // REMOTE QUERY
        frame().src = statsUrl   //this can't be null, might be caused by the lack of the other file.
        + '/graph/'
        + '?VanillaID=' + vanillaId
        + '&VanillaVersion=' + vanillaVersion
        + '&SecurityToken=' + securityToken
        + '&Range=' + range
        + '&DateRange=' + dateRange
```

**Comment by linc** [comment]
https://open.vanillaforums.com/discussion/33095/dashboard-stats-have-suddenly-stopped-showing-up#latest

**Comment by linc** [comment]
fyi vanillastats is in core.

**Comment by Caylus** [comment]
jamesinc on the forums:

"I tried the above steps and still experience the originally reported problem. I can see that the redirect is now working, however my dashboard reports other 404 errors for (on the analytics domain, https://analytics.vanillaforums.com/):

/applications/vanillastats/js/raphael.js
/applications/vanillastats/js/graph.js

If I intercept the code in loader.js where these scripts are loaded**, and rewrite the paths from vanillastats/ to vanillastatsapp/, the problem goes away and the graphs return.

**by script eval, I might add, which I think is a far from ideal way to be doing things - the 404 page on the analytics domain gets attempted eval by jQuery which leads to console errors, for one."

**Comment by DaazKu** [comment]
Sorry for that, we do not have that error on our demo site.
We are gonna redirect the whole directory.
