### ISSUE TITLE
Disqus: Callback URL must now match exactly

### ISSUE THREAD

**Issue by linc** [vanilla/addons#468]
Disqus tightened the security checks so the `redirect_url` has to match Disqus' Callback URL field exactly. Vanilla adds `?Target=<category>` to the `redirect_url` so the URL changes every time, causing mismatches.

We either need a workaround or to remove the Target redirect, which is annoying but not the end of the world.

Reference: https://disqus.com/home/discussion/channel-discussdisqus/api_invalid_parameter_redirect_uri_should_match_predefined_callback_uri/

**Comment by DaazKu** [comment]
I'm gonna try to do it this sprint.
