### ISSUE TITLE
Signatures should not count Emoji as images for restrictions

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/addons#484]
When images are restricted in signatures it also excludes emoji, which can be confusing for users since they don't always think of emojis as images.

**Comment by DaazKu** [comment]
Actually a real emoji would works fine 😀
The problem is with the fake ones `:)` which is replaced by <img src="https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/smile@2x.png" /> but is in reality and image :`<img src="https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/smile@2x.png" />`

**Comment by DaazKu** [comment]
We should actually start replacing the text emojis by real emojis instead of images. We updated the database to handle that not too long ago.

**Comment by linc** [comment]
It would be fine for Signatures to accommodate Emoji sets by skipping them in their count.
