### ISSUE TITLE
Role Titles addon needs to be updated in Addons Directory

### ISSUE THREAD

**Issue by bbrody** [vanilla/addons#493]
Role Titles plugin (v.1.0) doesn't work on Vanilla 2.4.200 installation. Webserver is Debian 8.8 with Apache 2.4, PHP 5.6.30 and MySQL 5.6

**Comment by webstey** [comment]
Doesn't seem to work on 2.3 either. Shows up at top of plugs list with an icon that says 'Mark Admin' when I drop it into the plugins folder.
