### ISSUE TITLE
Proposal: use same "release/x.y" branches as in main repo

### ISSUE THREAD

**Issue by R-J** [vanilla/addons#500]
Recently I tried to upload one of the plugins here to open.vanillaforums.com. That failed because the plugin had no license information.

One of the problems I had was that before I even could do so, I had to find out which branch has a version which is working with 2.3. By now I see three branches which I would have to inspect: "release/2.2", "2.3" and "master".

I found out that the working branch was master and then I made a pull request for quite a few plugins. But in the meantime the PluginInfo array has been transformed to json and so the master version of the plugin doesn't work anymore for Vanilla 2.3 and my pull request became somewhat useless (in the meantime I know enough git that there is something called "rebase" which wouldn't make that efforts useless. But all I know about that is this terminology, not the process)

I would love to see a "release/x.y" branch in the addons repo, at the same time as a release branch is created for the vanilla repo. That way,
a) making pull requests and
b) maintaining plugins on the community
would become easier.

I'm not sure if splitting a release/2.3 from the current addon repo is possible (although I think it would be great). But I see there is already a Vanilla release/2.4 branch and so I would welcome if at least the last branch before the first PluginInfo changes were made, could be made the addons release/2.4 branch.

It would be a shame if that process could only start for 2.5 (or nothing like that at all): there are some outdated plugins on the community page and the author of that broken plugins is always "Vanilla Staff" which is quite a bad reputation - and that is totally unneeded, because the working versions are all here *somewhere*...

That "somewhere" is really hard to explain to users. And when they download the zipped repo, the download a mixture of plugins: some being too old, some being too new and some in the right version, but there is no way to tell that by except for trial and error.

**Comment by linc** [comment]
Really the only thing stopping this is someone remembering to do it.

To do a retroactive branch, you'd need to rewind your repo to a known-good state for that release and create the branch. You could use `git reset --hard` and a HEAD hash to do this (assuming you have nothing unique on your local `master` branch since it would be lost).

You could judge this by looking at the date that 2.3 forked and finding the closest reasonable commit on the addons repo.

**Comment by linc** [comment]
We are now doing this.
