### ISSUE TITLE
Create new plugin CustomPockets plugin to flesh out custom location pocket feature

### ISSUE THREAD

**Issue by charrondev** [vanilla/addons#504]
Custom location pockets are a powerful feature used by theme developers to create small editable sections of the page for the client to edit. They don't really serve the same purpose as normal pockets. I propose that that their features be spun off into its own plugin to better serve developers and clients (**current functionality would still be left in the existing pocket plugin**).

The plugin would function similar to the custom location feature of the current Pockets plugin but with a few significant changes:

## Changes
- They would not be declared in a menu in the dashboard, but in a theme's themehooks file. Since these need to have a location explicitly declared in a theme anyway the configuration sits better in code, which can be checked into VCS instead of sitting in a database on the server.
- They would have key, name, and description instead of just a name. Referencing pockets by name, which can contain symbols and spaces, in code is a pain.
- They would be categorizable with headings per section for organization. This would be based on the structure of the config.
- They would have a config option to allow templating languages on a per Pocket basis. Currently Vanilla's templating engine is `Smarty`.
- They would allow default content to be declared inside of the theme in either PHP or Smarty.

## Default content example

```smarty
<body>
    {pocket name="Footer"}
        <footer>
            My default footer here
        </footer>
    {/pocket}
</body>
```

The content would remain a default value if nothing were specified in the dashboard and would aid in paintability of sites that have had their content done by a developer, but we want to make available to a client. It would also provide an easy way for clients to revert their pockets to a known working state should something go wrong.

**Comment by slafleche** [comment]
Having default content would be great. I'm not sure it really merits a new plugin though. We could add a few parameters to prevent a user from deleting theme specific pockets, adding a description etc.

**Comment by Charrondev** [comment]
That could work too. I think it would be important to be able to declare the pockets in say the config, and have them show up in the list though.

**Comment by slafleche** [comment]
You don't need to though. You could just add some parameters to the smarty function. That's a lot less work. I would personally prioritize having multilingual support and default value before any of the other features.

**Comment by chrisvanpatten** [comment]
I just want to jump into this — we use custom Pockets a ton for [our clients](https://tomodomo.co) on the hosted Vanilla platform so I have a lot of opinions!

Everything above sounds great except one thing: the idea of having to declare custom pockets in code.

While I love the idea on principle (the more in VCS the better! In fact I had been, at one point, working on an experimental tool that would let us define pockets in JS, then spoof an admin login to a Vanilla dashboard to set up and configure them via reverse-engineered POST requests and such), the sad reality is that most of our clients who use the hosted platform aren't on plans that have access to manipulate the theme hooks file.

Moving pocket config into code would basically render the feature useless for a huge chunk of our customers (who are also your customers), and really limit the capabilities of the Pockets system.

**Comment by slafleche** [comment]
@chrisvanpatten We're not suggesting to remove current functionality. 

I'm specifically talking about cases where we define a custom in a template for a client. Often times, those pockets have specific HTML needed to work. If the client deletes the pocket or the content, they don't know how to fix it.

**Comment by chrisvanpatten** [comment]
I know - that's exactly how I use custom pockets as well, and I've encountered the same issue. The problem is that if those custom pockets can only be registered via code in the future, which is how the proposal makes it sound.

**Comment by chrisvanpatten** [comment]
If the proposal is that registering custom pockets in themehooks.php is _in addition to_ the current functionality, that should be clarified. Right now, it sounds like the ability to add Pockets with custom locations via the UI would go away, and the Pockets UI would only be able to add pockets in the pre-defined locations instead.

**Comment by slafleche** [comment]
@chrisvanpatten Don't worry, any updates would be additional to current functionality.

**Comment by chrisvanpatten** [comment]
Woo! Thanks @slafleche!
