### ISSUE TITLE
Add icons to addons missing them.

### ISSUE THREAD

**Issue by Charrondev** [vanilla/addons#511]
Some of the addons in this repo do not have icons set. We should have icons for any currently used plugin in this repo that does not have one. If we don't use that plugin any more (and its not worth making an icon for) then we should consider deprecating it.

- [x] **CloudflareSupport** - This plugin modifies the Request object to work with Cloudflare.
- [x] **EmailPasswordSync** - Synchronizes passwords when users with the same email/password combos change their passwords.
- [x] **Bump** - Allows moderators to bump a discussion without commenting.
- [x] **AllowRawFormat** - Adds a permission to allow users with permission to post raw html.
- [x] **example** - Provides an example Development Pattern for Vanilla 2 plugins by demonstrating how to insert discussion body excerpts into the discussions list.
- [x] **FacebookID** - Displays users' Facebook IDs in various locations in the site.
- [x] **Forum Merge** - Merge another Vanilla 2 forum into this one.
- [x] **Forum Redirector** - Adds 301 redirects for Vanilla from common forum platforms. This redirector redirects urls from IPB, phpBB, punBB, smf, vBulletin, Lithium, and Xenforo
- [x] **HipChat** - HipChat integration, first version: Posts every new discussion to HipChat. Requires cURL.
- [x] **InvisibilityCloak** - Hide your forum from the prying eyes of search engines and bots while you set it up.
- [x] **Link Types** - Open external URLs in a new tab.
- [x] **LocaleDeveloper** - Contains useful functions for locale developers. When you enable this plugin go to its settings page to change your options.
- [x] **MathJax** - This plugin enables MathJax syntax in discussions and comments.
- [ ] **MeAction** - Allows IRC-style /me actions in the middle of comments as long as they appear at start of a new line.
- [x] **MessageLink** - Adds a link to message the author of each discussion and comment.
- [x] **Mollom** - Mollom spam protection integration for Vanilla.
- [x] **Necro** - Mark discussions raised from the dead.
- [x] **NoBump** - Allows moderators to add a comment without bumping a discussion.
- [x] **NoIndex** - Allows moderators & curators to mark a discussion as noindex/noarchive.
- [x] **postnumbering** - Add numerical indices, beside posts, that link to the post itself.
- [x] **PrefixDiscussion Filter** - Allow filtering of disussions by prefixes.
- [x] **SMF Compatibility** - Adds some compatibility functionality for forums imported from SMF.
- [x] **Solr** - Allows Vanilla's search functionality to use solr instead of MySQL fulltext search.
- [x] **Vanoogle** - A google search plugin for vanilla 2+
- [x] **welcomepost** - Redirect users, after registration, to an "introduce yourself" page that posts in a "welcome" category. This plugin does not work with the "approval" registration mode.

**Comment by danmaitland** [comment]
Some of these are done already and I'll chip away at the rest. You can view all the addon icons here: https://drive.google.com/drive/folders/0B1Bdmaaf1mxhWXN5M0FOUkRnT1E?usp=sharing

**Comment by danmaitland** [comment]
Ok all done. If you need the link to the icons just Hipchat me.
