### ISSUE TITLE
Release jsConnect 1.5.4 on the open source site

### ISSUE THREAD

**Issue by DaazKu** [vanilla/addons#513]
This will allow people to use jsConnectPHP v2
See https://github.com/vanilla/jsConnectPHP/issues/12

**Comment by DaazKu** [comment]
Done: https://open.vanillaforums.com/addon/jsconnect-plugin-1.5.4

**Comment by R-J** [comment]
That version already has been updated to work with the new dashboard and uses the `helpAsset` function. So it is incompatible with Vanilla 2.3: https://open.vanillaforums.com/discussion/33683/call-to-undefined-function-helpasset-while-trying-to-configure-jsconnect
