### ISSUE TITLE
Multilingual module can be seen by guests, but cannot be used by them

### ISSUE THREAD

**Issue by initvector** [vanilla/addons#515]
The Multilingual addon's "locale chooser" module allows users to select the locale they want to use on the site. It requires the `Garden.SignIn.Allow` permission for use, because the selected local is saved in metadata associated with the user account. Guests can see this module, even though they cannot use it. Attempting to choose a language as a guest throws an ugly "You need the Garden.SignIn.Allow permission to do that" error.

It would be great if this module didn't show up for guests, since they can't use it. It would be even better if the module could be updated to allow guests to set their locales, as well.

**Comment by slafleche** [comment]
Why not use a cookie when the user is signed out?

**Comment by linc** [comment]
@slafleche The cloud environment can't handle cookies guests due to our Varnish implementation.
