### ISSUE TITLE
[Pockets] Add description to pockets in the list in the dashboard

### ISSUE THREAD

**Issue by Charrondev** [vanilla/addons#527]
A common use for pockets is creating a section of the theme that is controlled by the client, but its name can only be so long and has to be referenced in the code where it is explicitly placed. It would help clients understand what each pocket does and leave a spot where the developer could leave instructions for the client on what to do with the pocket and its purpose.

This also reduces the likelihood of clients unintentionally disabling an important pocket.

**Comment by slafleche** [comment]
If we do improve pockets, I would also like to have a way to add default content through the theme somehow. For example, if we make a custom pocket for a dropdown, have a working example of what the markup should be.

**Comment by Charrondev** [comment]
Take a look at #504

**Comment by Charrondev** [comment]
Closing in favor of #565
