### ISSUE TITLE
Are there any addons in this repo that should be removed?

### ISSUE THREAD

**Issue by linc** [vanilla/addons#537]
@R-J @hgtonight @austins

**Comment by R-J** [comment]
What would be a reason to remove one of the plugins? The only reasons I could think of a plugin is broken or if it serves a purpose which is in core now.

In my opinion if one of the contained addons is broken, it should be fixed. If there is no interest in fixing it, it should still be kept, only added with a note. Maybe later on someone else would fix it. And it could still serve a) as an inspiration and b) as a code example.

**Comment by linc** [comment]
> What would be a reason to remove one of the plugins?

- Addon has become obsolete by core changes, another addon, or exterior changes. I think the two 'compatibility' addons may fall in this camp, now.
- Addon is broken  and no one cares enough to fix it. I suspect Mollom falls in this category.
- Addon has issues that are not resolvable or experience has taught us it wasn't as good an idea as we thought. Example: CustomizeText, Whispers.

> And it could still serve a) as an inspiration and b) as a code example.

Dead code should be used for neither, IMO. Our ecosystem is already littered with examples that are the opposite of a good idea and/or full of illegible code.

**Comment by Charrondev** [comment]
@linc Hasn't NBBC been rolled into core?

**Comment by Charrondev** [comment]
Reactions Stub is broken at the moment. It's purpose was to similulate the html structure of look of the proprietary Reactions plugin for theming purposes by people that used the hosted services but did not have access to the internal repositories. It has fallen out of sync with the actually reactions plugin by a good bit now, so no longer successully fulfills that purpose. 

I'm not sure how many people were using it for this, but I don't think its that many considering it doesn't work properly anymore. Right no it actually does more harm than good sitting in this repo (Someone can come along and theme that markup, that no longer resembes the markup of the real plugin). We should update it or remove it.

**Comment by DaazKu** [comment]
NBBC has been rolled into core, yes.

**Comment by charrondev** [comment]
We'll come and ask this again once we've updated to our deployment strategy (so we don't have to remove a million symlinks)
