### ISSUE TITLE
[Akismet] Edit flagged as spam put whole discussions in the spam queue

### ISSUE THREAD

**Issue by DaazKu** [vanilla/addons#550]
If you edit a discussion and the edit is flagged as spam, the while discussion is sent in the spam queue.

We have cases where moderators do a bad job and just empty the spam queue without reviewing it and this causes valid discussions with lots of comment to just vanish.

I spoke with @linc about it and he suggested that if a discussion has 10+ comments it should not be able to be tagged as spam.
I think we could maybe only put the edition in spam, as a change log.

We should put a little more though on the matter and find a way to mitigate this issue.

**Comment by initvector** [comment]
Issue moved to [vanilla/vanilla #5952](https://github.com/vanilla/vanilla/issues/5952) via [**ZenHub**](https://www.zenhub.com/)
