### ISSUE TITLE
"Content Manager" addon

### ISSUE THREAD

**Issue by linc** [vanilla/addons#557]
This addon will allow you to define special content detection rules in the Dashboard. Matching a defined rule will let you automatically perform a defined action. Think of it as inbox rules for a forum. 

## User stories:

* "I am getting a very specialized type of spam that is bypassing my other spam filters this week."
* "I would like a special notification if someone posts about X."
* "There is an easy formula for detecting rule-breaking on my forum that I would like to automate".
* "I am getting user applicants that are obviously spam and follow a pattern."
* "I would like to auto-approve a user if they say X in their applicant reason."

## Features / Technical:

In the Dashboard, add a menu item under "Moderation -> Content" named "Manage Rules". This is where rules will be created, edited, and deleted. It should use the same table-based design pattern as Flood Control. Follow the Dashboard style guide.

Rules are in the form: "When {recordtype.field} {condition} {pattern}, then {action}." They will be defined with dropdown menus.

It should hook its detection rules in the 'afterSave' events whenever possible.

### Record types:

* User.Reason ("applicant reason for joining")
* Discussion.Name ("discussion title")
* Discussion.Body|Comment.Body ("post")

### Condition:

* contains (string)
* starts with (string)
* ends with (string)
* matches the pattern (regex - this needs a sidebar help box)

### Actions:

* (if content) Move to spam queue.
* (If content) Delete it and Ban user.
* (if record is User.Reason) Decline the user.
* (if record is User.Reason) Approve the user.
* (any) Send me a message.
* (if Reporting2 enabled && it's content) Report it.

## Mockup of dashboard page:

![contentmanage](https://user-images.githubusercontent.com/117672/31852523-182ec922-b647-11e7-97ae-b13286d0a1c2.png)

## Limitations / Future:

* Only works on content as it is created.
* Maybe don't trigger on edits in v1. Thoughts?
* Is adding rules inline with a global save (vs a modal with a save) an antipattern?
* v2 idea: "Apply to last X hours of content" button when creating rules for easy mop up. Consider scaling implications - maybe a hard cap on how many it will check.
* v2 idea: Ability to disable a rule without deleting it.
* v2 idea: Ability to specify who to message (for that action).

**Comment by R-J** [comment]
There might be some logical AND/OR for Discussions necessary. As a start I would always assume AND if there is a rule for Discussion.Name and Discussion.Body

**Comment by R-J** [comment]
Activity posts and comments weren't in your design. I think it would make sense to include them, but for that there is the need to add two events to the ActivityModel: AfterSaveActivity and AfterSaveComment

What's your opinion on that?

**Comment by R-J** [comment]
I just started investigating how "MoveToSpamQueue" can be achieved and thought that basing the checks on the SpamModel instead of "AfterSave" events might be much more intuitive

**Comment by linc** [comment]
We plan to remove Activity in the future, so I wouldn't support that.
