### ISSUE TITLE
Minor pockets usability improvements

### ISSUE THREAD

**Issue by charrondev** [vanilla/addons#565]
Coming from https://github.com/vanilla/multisite/issues/153 we've decided we want some minor usability improvements for pockets now, and down the road we can do a more significant overhaul of Pockets.

## Features
- Descriptions
- Additional fields to fill programatically when creating a Pocket.

**Comment by linc** [comment]
This appears to duplicate https://github.com/vanilla/addons/issues/527, no?

**Comment by Charrondev** [comment]
I've closed out #527 in favour of this issue.
