### ISSUE TITLE
Ignore: Devolve permission check to Moderation.Manage 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/addons#587]
Ignore disallows users to ignore admins, which is good, but it would make sense for it to also stop users from ignoring Mods.

**Comment by shaunamcclemens** [comment]
Good news everyone! I was looking at this addon, and it seems there is a config setting in there that will accomplish this :) 

**Plugins.Ignore.AllowModeratorIgnore = false ** 

 I've tested this and it works perfectly on my demo. :) I think we can close this one out.
