### ISSUE TITLE
Quotes plug-in doesn't show attribution with 2.1b1 release and BBCode parser

### ISSUE THREAD

**Issue by pokrface** [vanilla/addons#60]
Per this thread on the forums:
http://vanillaforums.org/discussion/21843/quotesbbcode-bug-not-displaying-username-in-quote-2-1/p1

Version 1.6.1 of the Quotes plugin by Tim doesn't show attribution with InputFormatter set to bbcode. x00 found a fix, though. By editing `class.quotes.plugin.php` and changing `$Matches[2]` to `$Matches[3]` in `QuoteAuthorCallback`, the problem fixes itself.

Specific post with the fix detailed is here:
http://vanillaforums.org/discussion/comment/184114/#Comment_184114

**Comment by linc** [comment]
Was this fixed?
