### ISSUE TITLE
jsconnect should automatically sign in the user if they're signed in with provider

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#614]
If you are logged in to your SSO provider and then visit your forum, you get a "Sign in with (site name)" link that you can follow to get signed in. Why not have jsconnect immediately initiate the sign in process in this case?

Would need to ensure that is something is weird, the user doesn't end up in a redirect loop.

**Comment by varomix** [comment]
Hi
Are there any updates on this?
I was using jsConnect Auto SignIn plugin but is not working anymore, are there any ways to auto login users?

thank you
