### ISSUE TITLE
[Q&A] Enhance google SEO for questions and answers

### ISSUE THREAD

**Issue by charrondev** [vanilla/addons#619]
From @adrianspeyer 

>Saw this yesterday:
>
>![](https://us.v-cdn.net/5022541/uploads/editor/lp/eumvjjqjj3il.png "")
>
>It seems Google is now adding best answers into the search results for Quora & StackOverflow
>https://www.searchenginejournal.com/google-adds-carousel-quora-top-answers-search-results/248719/
>
>This seems how we could add it to our Q &A plugin:
>https://webmasters.stackexchange.com/questions/111242/how-do-i-implement-structured-data-for-questions-and-answers-to-get-best-answer?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
>
>Example of markup: 
>https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.quora.com%2FWhat-is-the-best-water-purifier-available-in-India%3Futm_medium%3Dorganic%26utm_source%3Dgoogle_rich_qa%26utm_campaign%3Dgoogle_rich_qa

**Comment by adrianspeyer** [comment]
More info
https://developers.google.com/search/docs/data-types/qapage

**Comment by adrianspeyer** [comment]
We really should be adding this - if possible.

**Comment by adrianspeyer** [comment]
@vrjrobitaille I am just commenting you on this, so it doesn't go stale

**Comment by qcybb** [comment]
Please add this in!

**Comment by vrjrobitaille** [comment]
Structured data for Q&A posts has been added - https://success.vanillaforums.com/kb/articles/417-release-2021-016#structured-data-for-qa-posts
