### ISSUE TITLE
QnA: Unanswered page category-following view filter

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/addons#629]
With QnA plugin enabled, navigating to discussions/unanswered 

**Filtering by Following**

![qna-following](https://user-images.githubusercontent.com/31856281/39012361-3abdb128-43e2-11e8-932d-4ad5eaf1b4a1.png)

**Filtering by All**
Redirects to discussions/discussions?save=1&followed=0

![qna-filtered](https://user-images.githubusercontent.com/31856281/39012410-5d533686-43e2-11e8-863d-a8e9c062af78.png)

**Comment by linc** [comment]
This also needs to check that the filter does NOT show up on similar plugins (Resolved, Ideation).

In core, the following filter should be made to be opt-in instead of opt-out.

**Comment by linc** [comment]
> only have the category index and recent discussions opt into filtering.
