### ISSUE TITLE
Welcome Post breaks APIv2 

### ISSUE THREAD

**Issue by slafleche** [vanilla/addons#638]
This plugin redirects event when registering a user through an API request.

Fix bug and mark plugin hidden.

**Comment by linc** [comment]
We generally have an issue wherein firing a redirect during a hook can cause API breaks. We're currently detecting `DELIVERY_TYPE_ALL` but that's insufficient to see if it's an API call. Part of the acceptance criteria for this issue will be identifying (and possibly implementing, if it's simple) a solution for safely detecting API calls in a generic way for issues like this.

We should also talk to the CSMs about whether we can remove this from circulation on cloud entirely. It's already not in the standard addons list, so marking as hidden would be redundant.

**Comment by linc** [comment]
The issue here is that this plugin will break when using the new API-based registration workflow shipping in 2.7. So there is no immediate breakage, but it will be rather severe when we do run across it.

**Comment by topcheese13** [comment]
@slafleche 

We are talking about this endpoint right ? 

![screen shot 2018-07-19 at 12 37 17 pm](https://user-images.githubusercontent.com/15312192/42957396-8e56a230-8b50-11e8-8af3-b24fa4bc33cb.png)

We only redirect you to the welcome post page in 2 places in the plugin

```
    /**
     * Redirect users to the /post/discussion end point after registration.
     */
    public function entryController_registrationSuccessful_handler($sender, $args) {
        if (!c('Garden.Registration.ConfirmEmail')) {
            $target = (Gdn::request()->post('Target')) ? '&Target='.Gdn::request()->post('Target') : null;
            redirectTo('/post/discussion?welcomepost=true'.$target);
        }
    }

    /**
     * When connecting through SSO, redirect user to the Welcome Post page.
     *
     * @param UserModel $sender
     * @param UserModel $args
     */
    public function userModel_afterSignIn_handler($sender, $args) {
        $target = (Gdn::request()->post('Target')) ? '&Target='.Gdn::request()->post('Target') : null;
        // AfterSignIn event is fired in several places, the InsertUserID
        // argument is only passed in the connect script.
        if (val('InsertUserID', $args)) {
            redirectTo('/post/discussion?welcomepost=true'.$target);
        }
    }
```

They both don't get triggered on an api call to `users/register`. What am I missing ?

**Comment by slafleche** [comment]
sorry, I should of put more context on my issue. I found the bug with the link user end point, the "targetUrl" was wrong. It wouldn't surprise me if it also broke elsewhere, but that's where I found it.

**Comment by topcheese13** [comment]
As per @slafleche.

this is the endpoint `/authenticate/link-user` we need to investigate.

**Comment by charrondev** [comment]
It seems like we're dropping the authenticate endpoints and new pages from the release (again), so this issue not really critical if this is the only endpoints affected.

**Comment by topcheese13** [comment]
>It seems like we're dropping the authenticate endpoints and new pages from the release (again), so this issue not really critical if this is the only endpoints affected.

This makes this issue a non-pressing one.

But, the problem is based on the fact that there is 2 redirects implemented in the WelcomePost.

```
/**
     * Redirect users to the /post/discussion end point after registration.
     */
    public function entryController_registrationSuccessful_handler($sender, $args) {
        if (!c('Garden.Registration.ConfirmEmail')) {
            $target = (Gdn::request()->post('Target')) ? '&Target='.Gdn::request()->post('Target') : null;
            redirectTo('/post/discussion?welcomepost=true'.$target);
        }
    }

    /**
     * When connecting through SSO, redirect user to the Welcome Post page.
     *
     * @param UserModel $sender
     * @param UserModel $args
     */
    public function userModel_afterSignIn_handler($sender, $args) {
        $target = (Gdn::request()->post('Target')) ? '&Target='.Gdn::request()->post('Target') : null;
        // AfterSignIn event is fired in several places, the InsertUserID
        // argument is only passed in the connect script.
        if (val('InsertUserID', $args)) {
            redirectTo('/post/discussion?welcomepost=true'.$target);
        }
    }
```

We will need a generic way of detecting if the call is an API call, to be used wherever we need it.

As per @initvector, we could simply implement a method that detects if the controller is an instance of `AbstractApiController`.

**Comment by initvector** [comment]
> As per @initvector, we could simply implement a method that detects if the controller is an instance of AbstractApiController.

This was moreso for a quick, dirty way to determine if a request is coming from an API v2 controller, specifically. API v2 controllers *should* be instances of `AbstractApiController`, but I don't know that will always be guaranteed. As discussed, [Vanilla checks the delivery method to determine its "is-API" flag](https://github.com/vanilla/vanilla/blob/91dedbb39db351132a51716a86dd0a5bbd422f4e/applications/dashboard/settings/class.hooks.php#L624) in other areas. A more robust solution, going forward, would likely be setting a relevant flag when the [API v2 route](https://github.com/vanilla/vanilla/blob/91dedbb39db351132a51716a86dd0a5bbd422f4e/bootstrap.php#L149) is fired from the dispatcher.
