### ISSUE TITLE
QnA: Announced Question will not show in the Unanswered Queue. 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/addons#640]
https://vanillaforums.teamwork.com/#tasks/9317198

If you create a new question, it will show up in the "unanswered" queue. If you announce that thread (In its category, or in its category and recent discussions) the question will still count against the number in unanswered, but the thread will not show if you look at the queue. 

Removing the question status fixes the count, and removing its announcement status allows it to appear in the unanswered queue.

**Comment by topcheese13** [comment]
I did a short investigation on this and I wanted to mention that the option to announce is not consistent around views when it comes to Q&A.

You can't announce on create.
You can announce on edit.
You can announce through the cog wheel option,

This makes me wonder if we wanted planned to allow announced question at all. The assumption is we didn't.

If we now want to we should consider the different implications around the platform other than the Unanswered queue.

**Comment by topcheese13** [comment]
I have confirmed this is not true.

>This makes me wonder if we wanted planned to allow announced question at all. The assumption is we didn't.

The problem comes from the render hook in the QnA plugin: https://github.com/vanilla/addons/blob/master/plugins/QnA/class.qna.plugin.php#L941

We are updating the DiscussionsController AnnounceData property changing it from an object to an array. Our different views expect an object for this specific data which make announcements not render in the unanswered endpoint.


I have updated the code to this for the sake of testing.

```
public function discussionsController_unanswered_render($sender, $args) {
        $sender->setData('CountDiscussions', false);

        // Add 'Ask a Question' button if using BigButtons.
        if (c('Plugins.QnA.UseBigButtons')) {
            $questionModule = new NewQuestionModule($sender, 'plugins/QnA');
            $sender->addModule($questionModule);
        }

        // Remove announcements that aren't questions...
        if (is_a($sender->data('Announcements'), 'Gdn_DataSet')) {
            $sender->data('Announcements')->result();
            $announcements = [];
            $announcementsObject = new Gdn_DataSet();
            foreach ($sender->data('Announcements') as $i => $row) {
                if (val('Type', $row) == 'Question') {
                    $announcements[] = $row;
                }
            }
            trace($announcements);
            $announcementsObject->importDataset($announcements);
            $sender->setData('Announcements', $announcementsObject);
            $sender->AnnounceData = $announcementsObject;
        }
    }
```

Announcements display correctly in the unanswered endpoint with the above code.
