### ISSUE TITLE
Error in QnA question/discussion state update logic

### ISSUE THREAD

**Issue by topcheese13** [vanilla/addons#643]
The problem
---
https://github.com/vanilla/addons/blob/master/plugins/QnA/class.qna.plugin.php#L557

In the QnA plugin we have a function named `recalculateDiscussionQnA` that gets called in multiple places in the plugin. For our case it gets call by this hook `commentModel_beforeUpdateCommentCount_handler` after somebody comments.

The logic of this function is faulty. 

```
$row = Gdn::sql()->getWhere('Comment',
            ['DiscussionID' => val('DiscussionID', $discussion), 'QnA is not null' => ''], 'QnA, DateAccepted', 'asc', 1)->firstRow(DATASET_TYPE_ARRAY);
```

The first step of the function is the above, we do a query to look for the first comment that matches our discussionID, that as a current QnA state of not null (the only possible states are NULL, Accepted and Rejected).

Let's say for the sake of our example that one answer has been posted and it has been marked as rejected, than a new answer is posted. By our query parameters, the rejected comment will be returned as `$row`.

From there we start the parsing of our returned row.

```
if (!$row) {
            if (val('CountComments', $discussion, 0) > 0) {
                $set['QnA'] = 'Answered';
            } else {
                $set['QnA'] = 'Unanswered';
            }

            $set['DateAccepted'] = null;
            $set['DateOfAnswer'] = null;
        } elseif ($row['QnA'] == 'Accepted') {
            $set['QnA'] = 'Accepted';
            $set['DateAccepted'] = $row['DateAccepted'];
            $set['DateOfAnswer'] = $row['DateInserted'];
        } elseif ($row['QnA'] == 'Rejected') {
            $set['QnA'] = 'Rejected';
            $set['DateAccepted'] = null;
            $set['DateOfAnswer'] = null;
        }
```

From this we are setting (or leaving as if you prefer) the QnA status of the question to Rejected , when it should be updated to Answered.

Info
---

Questions have 4 possible states `'Unanswered','Answered','Accepted','Rejected'`
Answers have 3 possible states `'Accepted','Rejected'` or NULL. Null means the answer hasn't been treated yet.

The fix
---
We have to review our logic. I would "recalculateDiscussionQnA" this way.

1. If we have any comment marked as Accepted. The question should be marked as Accepted. If we don't go to 2.

2. If we have any comment marked as NULL. The question should be marked as Answered. If we don't go to 3.

3. If the comment count on the question is bigger than 0. The question should be marked as Rejected. If it's not go to 4.

4. The question should be marked as Unanswered.

Extra problem
---

When we handle the rejection of an answer in function `discussionController_qnA_create()`
https://github.com/vanilla/addons/blame/master/plugins/QnA/class.qna.plugin.php#L409. We simply update the status of the question to Rejected. Which is false, we could have multiple answers waiting for treatment and rejecting one should consider the possibility of having a question still in Answered state. I believe that by fixing the problem above by changing our logic we could fix this one to by using the `recalculateDiscussionQnA()` function to update the status in the `discussionController_qnA_create()` method as well instead of updating it in a different way in this case. We already have a function that handles this why not use it. We were probably thinking at the time we would save a query by going straight to updating the question with the Rejected state but I showed it's wrong by explaining the above.

**Comment by linc** [comment]
This doesn't identify the user-facing problem. We're talking about a perceived logic problem without describing what the undesirable effect is that it's having, so I can't determine whether the analysis here is correct or not.

> From this we are setting (or leaving as if you prefer) the QnA status of the question to Rejected , when it should be updated to Answered.

So far, I don't agree with this assessment. If we have a 4th available Question status of 'Rejected', what other scenario would it be used in other than this one?

**Comment by linc** [comment]
Nevermind, I found the linked issue now.

So the issue doesn't appear to be the logic block, but rather the query. If there are new comments POST-rejection, it should count as Answered again.

**Comment by topcheese13** [comment]
>So the issue doesn't appear to be the logic block, but rather the query. If there are new comments POST-rejection, it should count as Answered again.

Yes

The problem is you need to know 2 things. Is there at least one accepted comment and if there isn't is there at least one NULL comment. So you need two queries that returns only one row. You could query all the comments and loop on them in PHP but I think 2 "first" row queries are better.

You can then apply the logic I've written above to determine the state once you have those 2 results. I don't see a better way of handling all the possible cases.
