### ISSUE TITLE
Customize text Blank page after saving changes.

### ISSUE THREAD

**Issue by rjadot** [vanilla/addons#66]
Hello

When I try using "Customize text" (customizetext) plugin with Vanilla forums 2.1.b1 or 2.1.b2,  after saving I got a blank page, and no change is saved.

I followed the process in the wiki, used default template and remove all plugins except for Customizetext, and the trie to generate logs with 

$Configuration['Garden']['Errors']['LogEnabled'] = TRUE;
$Configuration['Garden']['Errors']['LogFile'] = 'logs/error-log';
$Configuration['Garden']['Errors']['MasterView'] = 'deverror.master.php';

But nothing is generated.

I pulled the latest version of the plugin from git.

Are you already aware of such kind of bug? If not what could I do to report more informations?

Thanks

Raphaël

**Comment by linc** [comment]
Not supporting that addon any more.
