### ISSUE TITLE
QnA: accept my own comment as an answer

### ISSUE THREAD

**Issue by R-J** [vanilla/addons#67]
Just out of curiosity (and because I was annoyed from the reminder and because it is the truth: my comment has been the answer, I swear!) I tried to accept one of my comments over at vanillaforums.org as an answer by modyfing the url. I changed
"http://vanillaforums.org/discussion/qna/accept?commentid=SomeCommentID&tkey=MyTransientKey" to
"http://vanillaforums.org/discussion/qna/accept?commentid=MyOwnCommentID&tkey=MyTransientKey".
Although I received a message that I can not react on my own comments, my comment is now marked as an answer.

**Comment by beckyvb** [comment]
Some pull requests to close this one out:
https://github.com/vanilla/addons/pull/290
https://github.com/vanilla/internal/pull/367
Lets users accept their own answers.
