### ISSUE TITLE
debugbar shows error on enabling

### ISSUE THREAD

**Issue by R-J** [vanilla/addons#688]
When the plugin debugbar is enabled, it shows the error message "Failed stopping measure 'controller' because it hasn't been started".

Although there is no visual hint at this time, the plugin gets enabled (you have to reload the page to see it).

Since the message comes directly from the usage of the debugbar plugin itself, I assume it's a result that on base_render_before the plugin wasn't active.

**Comment by Kaspar-K** [comment]
https://github.com/vanilla/addons/issues/710
