### ISSUE TITLE
Civil Tongue does not work on Rich posts

### ISSUE THREAD

**Issue by charrondev** [vanilla/addons#709]
Civil Tongue works on rendered Text, TextEx, WYSIWYG, HTML, BBCode, & Markdown posts with base_filterContent_handler($sender, array $args), and filtering the $args['String'] event argument using some configurable regex's.

The Rich formatting doesn't run processHTML and as a result never fires this event.

**Comment by vrjrobitaille** [comment]
@charrondev Is this a duplicate of this - https://app.zenhub.com/workspaces/rd-kb-556cc3adbfcecd111b957933/issues/vanilla/addons/762 or are they different?
