### ISSUE TITLE
Whisper JS-Error

### ISSUE THREAD

**Issue by MaStr** [vanilla/addons#71]
Hi,
I installed latest stable 2.0 release: "Version 2.0.18.10"
and cloned the Addons-Folder. 

The current Whisper-Version "1.1.2" generates an JS-error on the default theme, which comes with 2.0 : 

> Uncaught TypeError: Object [object Object] has no method 'on' 

Which results into no displaying the receipants list after clicking on Whisper.

I assume that is an result of upgrading the the jquery version, isn't ?!

Matthias

**Comment by linc** [comment]
Whispers is no longer supported, sorry.
