### ISSUE TITLE
'Request' Toggle on Custom Badges

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/addons#800]
**Summary/Use-case**
- Client has a lot of custom badges for their community.  A lot of these are for specific contests or year-specific goals that the community runs. The issue that the mod/admin team on this site are running into is that users are requesting badges from wrong years or contests they weren't a part of.  Their solution is to turn off the badges that aren't currently 'active' but this removes those badges from the profiles of users that actually earned the badge.  

The idea for this feature would be to have a toggle implemented in each custom badges' settings that would allow the admin/mod team of a site to specify whether or not this badge is available to be requested or not.  This prevents users from requesting inactive badges but also keeps earned badges visible in user profiles (increases the gamification element of badges).

**Comment by tburry** [comment]
Great idea.

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #2418](https://github.com/vanilla/internal/issues/2418) via [**ZenHub**](https://www.zenhub.com/)
