### ISSUE TITLE
QnA unanswered count does not respect permissions

### ISSUE THREAD

**Issue by DaazKu** [vanilla/addons#803]
Related: https://github.com/vanilla/support/issues/567

The count function does a very basic count without any respect for permissions.
See: https://github.com/vanilla/addons/blob/fdd5ad6326d0ebdf2086dffa22da239f16454a20/plugins/QnA/class.qna.plugin.php#L939-L960

This causes the **Unanswered** section of the **Quick Links** bar to display results when a user should not have any:

![image](https://user-images.githubusercontent.com/2412909/80732919-ff5cd900-8ada-11ea-9dfe-d80c41157ab1.png)

In the above case a group (From our internal plugins) has an unanswered discussion and the user do not have access to it.

**Comment by dannimajdalani** [comment]
Closing this in favor of https://github.com/vanilla/support/issues/3224
