### ISSUE TITLE
jsConnect: what is "Make this connection your default signin method." supposed to do?

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#92]
The [code](https://github.com/vanilla/addons/blob/5f9d0c861476e404c49b730bce86b190c440b6ba/plugins/jsconnect/class.jsconnect.plugin.php#L79) seems to indicate that the only effect of making a connection the default is that that connection will *not* show Sign-in or Register links for guests, which seems like the opposite of what it should be...

**Comment by linc** [comment]
It makes the normal Sign In links redirect, so the additional ones would be redundant. It also makes the `/sso` endpoint work for that connection. See http://docs.vanillaforums.com/features/sso

**Comment by JasonBarnabe** [comment]
@linc If I check it though, and I visit my forum when not logged in (to the forum or to the SSO providing site), I get:

"Howdy, Stranger!

It looks like you're new here. If you want to get involved, click one of these buttons!"

And then there's no buttons.

**Comment by linc** [comment]
Is your registration method set to "Connect"?

**Comment by linc** [comment]
I'll add that I'm looking at this on 2.2 (master) and it's working exactly correct, so it could be some unfixed bug in 2.1 that's causing that.

**Comment by JasonBarnabe** [comment]
Yes, registration method is "Connect".

Pulled from 2.1, it acts as I describe. Pulled from master, the buttons show up. So it does appear to be something fixed in 2.2. Is something that (c/sh)ould be fixed in the next 2.1?

**Comment by linc** [comment]
Let me put it this way: If someone wants to open the pull requests to get it patched in 2.1, I'm happy to accept it. Right now, my focus is on getting 2.2 jumpstarted, so I'm not really concerned about tickets open solely against 2.1.
