### ISSUE TITLE
jsConnect: sign out URL does nothing

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#93]
Specifying a Sign Out URL seems to do nothing. Upon signing out, this URL is never visited; the user is only signed out of the forum.

**Comment by linc** [comment]
Did you specify the connection as Default? That should cause it to redirect to your sign out after the forum sign out.

**Comment by JasonBarnabe** [comment]
No, it's not default, see https://github.com/vanilla/addons/issues/92.

**Comment by JasonBarnabe** [comment]
This works in master, but not 2.1.
